version: 1
type: infra
component:
  name: synthetic-test-support
  service: synthetic-test-support
  team: QA
  description: Framework to create synthetic test as code
  domain: platform
  slackChannel: '#cir_tribe_tech_pf'
