include:
  project: dx/pipelines
  file:
    - /kotlin/kotlin-sdk.yml
    - /jobs/sonarscan-dev-edition.yml

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

stages:
  - build
  - post-build
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  ENABLE_APPROVABOT: "true"

lint:
  image: 824725208937.dkr.ecr.eu-central-1.amazonaws.com/personio-jdk:1.3.0
  stage: build
  script:
    - ./gradlew ktlintCheck

test:unit:
  image: 824725208937.dkr.ecr.eu-central-1.amazonaws.com/personio-jdk:1.3.0
  stage: build
  tags:
    - dev
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/test-results/test/xml/jacocoReport.xml
    expire_in: 1 day

test:e2e:
  image: 824725208937.dkr.ecr.eu-central-1.amazonaws.com/personio-jdk:1.3.0
  stage: post-build
  needs: []
  dependencies: []
  script:
    - ./gradlew e2eTest
  tags:
    - dev
  variables:
    AWS_PROFILE: dev
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - "build/reports/tests/e2eTest/*"

sonarscan:
  extends:
    - .sonarscan-kotlin
  stage: post-build
  needs:
    - test:unit
