---
name: "📕 Documentation Issue"
description: Report an issue in the Synthetic Test Support documentation
title: "[Documentation]: "
labels: [documentation, needs-triage]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Include links to the affected documentation page(s).
    validations:
      required: true
